export const env = {
  failureInjectionEnabled: ['1', 'true', 'yes', 'on'].includes((process.env.FAILURE_INJECTION_ENABLED || '').trim().toLowerCase()),
  failureInjectionTaskTypes: process.env.FAILURE_INJECTION_TASK_TYPES || '',
  failureInjectionErrorCodes: process.env.FAILURE_INJECTION_ERROR_CODES || '',
  failureInjectionRatio: Number(process.env.FAILURE_INJECTION_RATIO || 0),
  port: Number(process.env.PORT || 60000),
  host: process.env.HOST || '127.0.0.1',
  dataFile: process.env.DATA_FILE || 'data/app.db',
  staticDir: process.env.STATIC_DIR || '../frontend/dist',
  jwtSecret: process.env.JWT_SECRET || 'change-me-in-production',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || '7d',
  aiProvider: process.env.AI_PROVIDER || 'mock',
  aiTextEndpoint: process.env.AI_TEXT_ENDPOINT || '',
  aiImageEndpoint: process.env.AI_IMAGE_ENDPOINT || '',
  aiVideoEndpoint: process.env.AI_VIDEO_ENDPOINT || '',
  aiAudioEndpoint: process.env.AI_AUDIO_ENDPOINT || '',
  aiTimeoutMs: Number(process.env.AI_TIMEOUT_MS || 45000),
  aiAuthHeader: process.env.AI_AUTH_HEADER || 'Authorization',
  aiApiKey: process.env.AI_API_KEY || '',
  modelSecretKey: process.env.MODEL_SECRET_KEY || 'change-me-model-secret-key',
  aiMaxRetries: Number(process.env.AI_MAX_RETRIES || 2),
  aiRetryDelayMs: Number(process.env.AI_RETRY_DELAY_MS || 600),
  videoMaxConcurrent: Number(process.env.VIDEO_MAX_CONCURRENT || 2),
  ffmpegBin: process.env.FFMPEG_BIN || 'ffmpeg',
  videoMergeOutputDir: process.env.VIDEO_MERGE_OUTPUT_DIR || 'data/video-merges',
  videoMergeEngine: (process.env.VIDEO_MERGE_ENGINE === 'placeholder' ? 'placeholder' : 'ffmpeg') as 'placeholder' | 'ffmpeg',
  queueDriver: (process.env.QUEUE_DRIVER === 'external' ? 'external' : 'internal') as 'internal' | 'external',
  queueBackend: (process.env.QUEUE_BACKEND === 'bullmq' ? 'bullmq' : 'lease') as 'lease' | 'bullmq',
  queueRedisUrl: process.env.QUEUE_REDIS_URL || process.env.REDIS_URL || 'redis://127.0.0.1:6379',
  queueName: process.env.QUEUE_NAME || 'human2-video-tasks',
  queueLoopEnabled: process.env.QUEUE_LOOP_ENABLED !== '0',
  queueLeaseOwnerId: process.env.QUEUE_LEASE_OWNER_ID || `proc-${process.pid}`,
  queueLeaseTtlMs: Number(process.env.QUEUE_LEASE_TTL_MS || 6000),
  unifiedAlertNotificationEnabled: ['1', 'true', 'yes', 'on'].includes(
    (process.env.UNIFIED_ALERT_NOTIFICATION_ENABLED || '').trim().toLowerCase()
  ),
  unifiedAlertNotificationEndpoint: process.env.UNIFIED_ALERT_NOTIFICATION_ENDPOINT || '',
  unifiedAlertNotificationAuthHeader: process.env.UNIFIED_ALERT_NOTIFICATION_AUTH_HEADER || '',
  unifiedAlertNotificationTimeoutMs: Number(process.env.UNIFIED_ALERT_NOTIFICATION_TIMEOUT_MS || 5000),
  unifiedAlertNotificationMaxRetries: Number(process.env.UNIFIED_ALERT_NOTIFICATION_MAX_RETRIES || 3),
  unifiedAlertNotificationRetryBaseDelaySeconds: Number(process.env.UNIFIED_ALERT_NOTIFICATION_RETRY_BASE_DELAY_SECONDS || 30)
};
