export const BIZ_CODE = {
  OK: 'OK',
  INVALID_QUERY: 'INVALID_QUERY',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_OPERATION: 'INVALID_OPERATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  QUEUE_FULL: 'QUEUE_FULL',
  CAPABILITY_MISMATCH: 'CAPABILITY_MISMATCH',
  MODEL_NOT_SUPPORTED: 'MODEL_NOT_SUPPORTED',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type BizCode = (typeof BIZ_CODE)[keyof typeof BIZ_CODE];
